name: Pylint

on:
  push:
    branches:
      - main
      - stage
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Starting deployment for branch: ${{ github.ref_name }}"
          
          if [[ "${{ github.ref_name }}" == "stage" ]]; then
            echo "Running Stage deployment..."
            bash /etc/wesolved/build/scripts/stage-deploy.sh
            
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Running Production deployment..."
            bash /etc/wesolved/build/scripts/main-deploy.sh
            
          else
            echo "Invalid branch. Exiting..."
            exit 1
          fi
          
          echo "Deployment complete!"

